[package]
name = "automization_script"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
inquire = "0.6"
chrono = "0.4.38"
terminal_size = "0.3.0"
nix = "0.26"
colored = "2.1.0"
dialoguer = "0.11.0"